# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Appium Server Action
  # You may pin to the exact commit or the version.
  # uses: moatazeldebsy/Appium-Server-GitHub-Action@05d9d683e555e7636d68a48360f1cf7c117ddda5
      uses: moatazeldebsy/Appium-Server-GitHub-Action@V1.0.5
    - name: Build with Maven
      run: mvn test -DdefaultSuiteFiles="./testng.xml,"
