# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: install appium
      uses: actions/setup-node@v1
    - run: npm install -g appium
      
    - name: install Win App driver
      uses: actions/setup-node@v1
    - run: npm install -g appium-windows-driver
    
    - name: Build with Maven
      run: mvn test -DdefaultSuiteFiles="./testng.xml,"
